# Generated by Django 3.2.16 on 2023-01-06 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_comment_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved',
        ),
    ]
